# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 940a160285e40b05b058245556e05b6086e0f1468adaff96a265c70f0383353cdf0bfcc58228fd8d4889b7af6e7dbdd8ae255bf51b7b8d60f6e6577707fcb6b7

test:
  secret_key_base: cad506cfe1644a4f832b5b93b9e6fa016edf6800992979e0be6b879c2dde623298a42aab4324a9e371952420be7304de71352974fa66708c9651556334039dd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
